language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_f4194fa89ee2_key -iv $encrypted_f4194fa89ee2_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
